loanOnPhone/urls.py
from django.contrib import admin
from django.urls import path
from loanPhoneApp import views
urlpatterns = [
    path('admin/', admin.site.urls),

    #Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),


    #Loan Applications
    path('', views.home, name='home'),
    path('apply/', views.applyLoan, name='applyLoan'),
    path('successfull/', views.successloan, name='successloan'),

]

loanPhoneApp/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class loanModel(models.Model):
    Name =          models.CharField(max_length=50, blank=False)
    phone_regex =   RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number =  models.CharField(validators=[phone_regex], max_length=17, null=False, unique=True)  # validators should be a list
    identity_no =   models.IntegerField(null=False, unique=True)
    Address =       models.CharField(max_length=300 , blank=False)
    reason =        models.TextField(blank=False)
    created_at =       models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.Name

loanPhoneApp/forms.py
from django.forms import ModelForm
from .models import loanModel

class LoanForm(ModelForm):
    class Meta:
        model = loanModel
        fields = ['Name', 'phone_number', 'identity_no', 'Address', 'reason']

loanPhoneApp/views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from .forms import LoanForm
from django.contrib.auth.decorators import login_required


# Create your views here.

def home(request):
    return render(request, 'loanPhoneApp/home.html')

def signupuser(request):
    if request.method == 'GET':
        return render(request, 'loanPhoneApp/signupuser.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('applyLoan')
            except IntegrityError:
                return render(request, 'loanPhoneApp/signupuser.html',
                              {'form': UserCreationForm(), 'error': 'Username already exist'})
        else:
            return render(request, 'loanPhoneApp/signupuser.html', {'form': UserCreationForm(), 'error':'Passwords did not match'})


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'loanPhoneApp/loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])

        if user is None:
            return render(request, 'loanPhoneApp/loginuser.html', {'form': AuthenticationForm(), 'error':'Wrong credentials'})
        else:
            login(request, user)
            return redirect('applyLoan')

@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

@login_required
def applyLoan(request):
    if request.method == 'GET':
        return render(request, 'loanPhoneApp/applyLoan.html', {'form':LoanForm()})
    else:
        try:
            form = LoanForm(request.POST)
            formtouser = form.save(commit=False)
            formtouser.user = request.user
            formtouser.save()
            return redirect('successloan')
        except ValueError:
            return render(request, 'loanPhoneApp/applyLoan.html', {'form': LoanForm(), 'error': 'Uh-oh bad data passed!'})

@login_required()
def successloan(request):
    return render(request, 'loanPhoneApp/successloan.html')

loanPhoneApp/templates/loanPhoneApp/applyLoan.html
{% extends 'loanPhoneApp/base.html' %}

{% block content %}

<div class="row justify-content-center mt-5">

     <div class="col-md-5">
            <h2>Apply For Loan Here</h2>
        </div>

</div>

<div class="row justify-content-center mt-5">

    <div class="col-md-5">

        {% if error %}

            <div class="alert alert-danger" role="alert">
                    {{ error }}

        {% endif %}

          <form method="POST">
            {% csrf_token %}

              <div class="form-group">
                  <label for="id_Name">Name:</label>
                  <input type="text" name="Name" class="form-control" id="id_Name" required>
              </div>

              <div class="form-group">
                  <label for="id_phone_number">Phone number:</label>
                  <input type="text" name="phone_number" class="form-control" id="id_phone_number" required>
              </div>

              <div class="form-group">
                  <label for="id_identity_no">Identity no:</label>
                  <input type="text" name="identity_no" class="form-control" id="id_identity_no" required>
              </div>

              <div class="form-group">
                  <label for="id_Address">Address:</label>
                  <input type="text" name="Address" class="form-control" id="id_Address" required>
              </div>

              <div class="form-group">
                  <label for="Reason:">Reason:</label>
                  <textarea type="text" name="reason" class="form-control" id="id_reason" required></textarea>
              </div>

            <button type="submit" class="btn btn-primary">Submit</button>
</form>

        </div>
     </div>

</div>

{% endblock %}

loanPhoneApp/templates/loanPhoneApp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Loan On Phone</title>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-light bg-warning">
<div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">
         <img src="{% static 'loanPhoneApp/testlogo.png' %}" width="30" height="30" class="d-inline-block align-top">
        <span>Loan On Phone</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">

<ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item mt-2">
                    <p>Logged in as {{ user }}</p>
                </li>
                <li class="nav-item">
                    <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
                    <form style='display: none;' method="POST" action="{% url 'logoutuser' %}">
                        {% csrf_token %}
                        <button id="signOutBtn" type="submit">Logout</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signupuser' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
                </li>
            {% endif %}
        </ul>
      </div>
</div>
</nav>

    <div class="container">

        {% block content %}{% endblock %}

    </div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

loanPhoneApp/templates/loanPhoneApp/home.html
{% extends 'loanPhoneApp/base.html' %}

{% block content %}

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">

                 <h1>Get Your Loan On Phone!</h1>
            <p>Need fund to start your business or financial assistance?
                No problem! Get your loan approve in 24hrs with flexible tenure ranging from 6 to 36 months.
                <b><i>No security or collateral required.</i></b>
                Live that life that matters most to you. Your new organized life awaits.</p>

            {% if user.is_authenticated %}

                <a role="button" class="btn btn-primary btn-lg" href="{% url 'applyLoan' %}">Start</a>

             {% else %}

                <a role="button" class="btn btn-primary btn-lg" href="{% url 'signupuser' %}">Start</a>

            {% endif %}


        </div>
    </div>

{%  endblock %}

loanPhoneApp/templates/loanPhoneApp/loginuser.html
{% extends "loanPhoneApp/base.html" %}


{% block content %}

<div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Login</h2>
        </div>
    </div>

<div class="row justify-content-center mt-5">

    <div class="col-md-5">

        {% if error %}

            <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>

        {% endif %}


        <form method="POST">
        {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" class="form-control" id="username">
            </div>

             <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>

            <button type="submit" class="btn btn-primary">Login</button>

        </form>
        <hr>

        <div class="text-center">
            Need an account? <a href="{% url 'signupuser' %}">Sign Up here</a>
        </div>

  </div>

</div>

{% endblock %}

loanPhoneApp/templates/loanPhoneApp/signupuser.html
{% extends "loanPhoneApp/base.html" %}

{% block content %}

<div class="row justify-content-center mt-5">

    <div class="col-md-5">
        <h2>Sign Up</h2>
    </div>

</div>

<div class="row justify-content-center mt-5">

    <div class="col-md-5">
        {% if error %}

            <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>

        {% endif %}

        <form method="POST">

             {% csrf_token %}

              <div class="form-group">
                <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                    <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
                </div>

                <div class="form-group">
                    <label for="password1">Password</label>
                    <input type="password" name="password1" class="form-control" id="password1">
                </div>

                <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input type="password" name="password2" class="form-control" id="password2">
                </div>

                <button type="submit" class="btn btn-primary">Sign Up</button>

                </form>
                <hr>

                 <div class="text-center">
                Do you already have an account? <a href="{% url 'loginuser' %}">Login here</a>
            </div>

    </div>

</div>

{% endblock %}

loanPhoneApp/templates/loanPhoneApp/successloan.html
{% extends 'loanPhoneApp/base.html' %}

{% block content %}

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">

                 <h1>Thank You,</h1>
            <p>Your application has been submitted successfully. Our executives will contact you in 24hrs. Till that
                <b><i>sit and relax.</i></b>
            </p>
        <a role="button" class="btn btn-primary btn-lg" href="{% url 'home' %}">Home</a>
        </div>
    </div>

{%  endblock %}